---
classes:
  - exercises:
      - title: Lab 1 - minikube usage
        file: ../tp/tp1-minikube.md
      - title: Lab 2 - kubectl run
        file: ../tp/tp2-kubectl.md
      - title: Lab 3 - Deployment
        file: ../tp/tp3-deployment.md
      - title: Lab 4 - Service and test
        file: ../tp/tp4-service.md
      - title: Lab 5 - Ingress
        file: ../tp/tp5-ingress.md
